export class Installation {
    remarks: string = '';
    vehicleId:string='';
    vehicleMakeId:string='';
    vehicleModelId:string='';
    vehicleclassid:string = '';
    vehicleRegNo:string='';
    vehicleChasisNo:string='';
    vehicleEngineNo:string='';
    vehicleMfgYear:string='';
    vehicleStateCode:string='';
    deviceimeino:string='';
    vehicleRtoId:string='';
    vehicleType:string ='';
    customerId:string='';
    customerMobileNo:string='';
    deviceId:string='';
    uploadedby:string='';
    idProof:string='';
    addressProof:string='';
    rcFile:any;
    customerName:string='';
    customerAddress:string='';
    rcNo:string='';
    invoiceNo:string='';
    panicNo:string='';
    installedDate:string='';
    deviceTypeId: string = '';
    installedBy:string='';
    dob:string='';
    mobilize;
    fuel;
    ac;
    vehicleIconId:string='';
    idproofName:string='';
    idproofpath:string='';
    addressroofname:string='';
    addressproofpath:string;
    devicefilepath:string='';
    vehiclefilepath:string='';
}